### PR TITLE
Reason for using Squid on Stratum 1

### LINKED ISSUE #12: clarify reason to add reverse Squid proxy to Stratum 1
We're currently setting up a Squid proxy on the Stratum 1 server, as is recommended at https://cvmfs.readthedocs.io/en/stable/cpt-replica.html#recommended-setup, but we don't mention why we're doing this.

The docs mention:

* reduce points of failure: that's not entirely clear to me... I guess it helps a little when CVMFS itself would die on Stratum 1?
* caching of Geo API calls (are we actually doing this in the current configuration?)
* anything else?

cc @jblomer, @rptaylor

### PR DESCRIPTION
**Pull request by bedroge**
Closes #12.

### CODE REVIEW

**Comment by bedroge** [comment]
@jblomer @drdaved I've added a small bit of explanation about the Squid with this PR, could you perhaps take a look if this is correct? Is the argument for scaling out, as Jakob mentioned in #12, also a valid one? And would that work as described, by having one load balancer listening on ports 80/8000, which redirects the traffic to different Squids (listening on different ports) on that machine?

**Comment by jblomer** [comment]
Looks good to me

**Review by boegel — APPROVED** [review]
lgtm, thanks for the feedback @jblomer!

**Comment by DrDaveD** [comment]
I agree it looks ok.

**Pull request merged**
